// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Ssh.Helpers.KeyVault.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// List of secrets
    /// </summary>
    public partial class SecretListResult
    {
        /// <summary>
        /// Initializes a new instance of the SecretListResult class.
        /// </summary>
        public SecretListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SecretListResult class.
        /// </summary>
        /// <param name="value">The list of secrets.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// secrets.</param>
        public SecretListResult(IList<Secret> value = default(IList<Secret>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the list of secrets.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<Secret> Value { get; set; }

        /// <summary>
        /// Gets or sets the URL to get the next set of secrets.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
